#!/usr/bin/env zsh
autoload -Uz @zpm-get-plugin-name @zpm-get-plugin-path

plugins=$@
if [[ -z $plugins ]]; then
  plugins=('zpm')
fi

for plugin in $plugins; do
  local readme
  local Plugin_name=$(@zpm-get-plugin-name "$1")
  local Plugin_path=$(@zpm-get-plugin-path "$Plugin_name")

  if [[ -f  "${Plugin_path}/README.md" ]]; then
    readme="${Plugin_path}/README.md"
  elif  [[ -f  "${Plugin_path}/readme.md" ]]; then
    readme="${Plugin_path}/readme.md"
  fi

  md "${readme}"
done
