#!/usr/bin/env zsh
autoload -Uz _ZPM_get_plugin_name _ZPM_get_plugin_path

plugins=$@
if [[ -z $plugins ]]; then
  plugins=('zpm')
fi

for plugin in $plugins; do
  local readme
  local Plugin_name=$(_ZPM_get_plugin_name "$1")
  local Plugin_path=$(_ZPM_get_plugin_path "$Plugin_name")

  if [[ -f  "${Plugin_path}/README.md" ]]; then
    readme="${Plugin_path}/README.md"
  elif  [[ -f  "${Plugin_path}/readme.md" ]]; then
    readme="${Plugin_path}/readme.md"
  fi

  md "${readme}"
done
